spring:
  data:
    rest:
      base-path: /data-api
  application:
    name: taco-shop
  datasource:
    url: jdbc:postgresql://localhost:5432/taco_shop
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  rabbitmq:
    template:
      exchange: tacocloud.order
      routing-key: kitchens.central
taco:
  orders:
    pageSize: 10